### ISSUE TITLE
User Story - CTA Section

### ISSUE THREAD

**Issue by ShaneDoyleDev** [ShaneDoyleDev/fleetfoot#10]
# EPIC: **User Interaction and Content Engagement**

As the **site owner**, I can **have a CTA section to entice shoppers to sign up with their email addresses**, so that **I can send them emails of the latest deals and offers of the store for marketing purposes for generating repeat sales.**.

T-Shirt Size: **M**

## **Acceptance Criteria**

- There is an area featured on the homepage enticing users to signup for an account.
- A form in for email input is present.
- The text heading is clear in its purpose and catchy in its messaging.
- Section is responsive and remains easy to read and interact with on smaller screens.
- Content is positioned next to eye catching imagery that reinforces the sites design.
- The CTA section is responsive for smaller screens.

## **Tasks**

- [ ] Design a CTA section on the homepage.
- [ ] Create an appropriate image to use for the section.
- [ ] Have an email input form so users can subscribe.
- [ ] Ensure that the section is responsive and remains easy to read on smaller screens.
