### ISSUE TITLE
User Story - View Transaction Total

### ISSUE THREAD

**Issue by ShaneDoyleDev** [ShaneDoyleDev/fleetfoot#11]
# **EPIC**: **Viewing and Navigation**

As a **user**, I can **quickly see my total purchases during my time shopping on the store** so that **I can assess how much I have spent in case I may have gone over my budget**.

T-Shirt Size: **M**

## **Acceptance Criteria**

- The customer grand total is shown next to the cart symbol on the main navigation.
- The user can see their total from the shopping cart page.
- The total spent will be displayed in the user's order summary after a transaction has been made.
- A popup will be displayed after a customer has added or removed an item from their shopping bag with the updated total amount in their cart.

## **Tasks**

- [x] Update the main navigation to show the customer grand total next to the cart symbol.
- [x] Modify the shopping cart page to display the user's total.
- [x] Ensure the total spent is displayed in the user's order summary after a transaction.
- [x] Implement a popup feature that displays the updated total amount when an item is added or removed from the shopping bag.
- [x] Write the logic to calculate the total in the context processor for the cart data.
