### ISSUE TITLE
User Story - Product Wishlist

### ISSUE THREAD

**Issue by ShaneDoyleDev** [ShaneDoyleDev/fleetfoot#16]
# EPIC: **User Interaction**

As a **user**, I can **manage my wishlist** to **save items for future purchase and easily add them to my shopping cart**.

T-Shirt Size: **L**

## **Acceptance Criteria**

- Have a link in the main navbar that takes the user to their own wishlist page.
- On the wishlist page, the user can see a list of all items in their wishlist and can select and add them to their shopping cart for purchase.
- Have a clickable heart icon next to the product card and product detail page that allows the user to click and add the product to their wishlist.
- Create a database table to model and persist this data so that the user can access it in the future.
- When the user clicks the icon, it changes from a heart outline to a filled heart to notify the user.
- When the user clicks the icon when unchecked, a pop-up will notify them that the item has been successfully added to their wishlist.
- When the user clicks the icon when checked, a pop-up will notify them that the item has been successfully removed from their wishlist.
- There is a section of the website where the user can see their wishlist and from there they may add items to the cart.

## **Tasks**

- [ ] Add a link in the main navbar to the user's wishlist page.
- [ ] Create the wishlist page to display all items in the user's wishlist.
- [ ] Implement functionality to add items from the wishlist to the shopping cart.
- [ ] Add a clickable heart icon to product cards and product detail pages.
- [ ] Create a database table to model and persist wishlist data.
- [ ] Implement visual feedback for the heart icon to show when an item is added or removed from the wishlist.
- [ ] Implement pop-up notifications for adding and removing items from the wishlist.
- [ ] Test the wishlist functionality and user interface to ensure proper operation.
