### ISSUE TITLE
User Story - Product Card

### ISSUE THREAD

**Issue by ShaneDoyleDev** [ShaneDoyleDev/fleetfoot#17]
# EPIC: **Viewing and Navigation**

As a **user**, I can **view articles as clickable product cards with images of the shoe and information** so that **I can easily discover and navigate to products I'm interested in**.

T-Shirt Size: **M**

## **Acceptance Criteria**

- Each article is represented by a card with an image of the shoe.
- Cards are clickable, leading to the corresponding product detail page.
- The design of the cards is visually appealing and consistent with the shop's theme.
- The product card shows the name, gender, rating, and price of the shoe.

## **Tasks**

- [ ] Design the article card layout.
- [ ] Implement functionality to query the product to retrieve the corresponding shoe content for the detail page.
- [ ] Make product cards clickable to direct the user to the product detail page.
- [ ] Display the matching shoe image on top.
- [ ] Show the shoe name, gender, rating, and price below the image.
- [ ] Ensure the design of the product cards is visually appealing and consistent with the shop's theme.
- [ ] Test the functionality and appearance of the product cards to ensure they meet the acceptance criteria.
