### ISSUE TITLE
User Stories - Product Sort Bar

### ISSUE THREAD

**Issue by ShaneDoyleDev** [ShaneDoyleDev/fleetfoot#19]
# EPIC: **Sorting and Filtering**

As a **user**, I can **sort the products by price** to **easily find shoes within my budget or preference**.

T-Shirt Size: **M**

## **Acceptance Criteria**

- Feature a drop-down menu that allows the user to sort by either price or rating.
- Products can be sorted in both ascending and descending order.
- Clicking the drop-down automatically triggers the sorting functionality.

## **Tasks**

- [x] Add a drop-down menu for sorting options on the products list page.
- [x] Implement sorting functionality for both price and name in the view.
- [x] Ensure the sorting works for both ascending and descending order.
- [x] Make sure clicking the drop-down automatically triggers the sorting functionality using Javascript.
- [x] Test the sorting feature to ensure it meets the acceptance criteria.
