### ISSUE TITLE
User Story - View Products

### ISSUE THREAD

**Issue by ShaneDoyleDev** [ShaneDoyleDev/fleetfoot#2]
# EPIC: **Viewing and Navigation**

As a **user**, I can **see a main product page that allows me to view shoes in the store** so that **I can see a list of footwear the store is selling**.

T-Shirt Size: **L**

## **Acceptance Criteria**

- Clicking on the gender in the main nav takes the user to the products page for all shoes relating to that chosen gender.
- All shoes for the chosen gender are rendered as a list of product cards.
- Pagination is provided on the page to limit too many number of search results shown at once.
- Products are rendered in a responsive grid that adapts to the user's screen size.

## **Tasks**

- [ ] Create the template for showing all products to the site user.
- [ ] Implement the view logic to display the list of products to the user.
- [ ] Implement pagination functionality to limit the number of results at any one time.
- [ ] Ensure the products page is responsive for smaller screens.
