### ISSUE TITLE
User Stories - Shoe Size Selection

### ISSUE THREAD

**Issue by ShaneDoyleDev** [ShaneDoyleDev/fleetfoot#20]
# EPIC: **Purchasing and Checkout**

As a **user**, I can **easily see and select the correct shoe size when shopping** to **ensure I can easily select the correct shoe size**.

T-Shirt Size: **M**

## **Acceptance Criteria**

- Render a grid of clickable shoe sizes on the product detail page that the user can select from.
- The correct shoe sizes are shown for each individual shoe.
- Clicking on a shoe size will add the correct shoe and corresponding size to the shopping cart.
- Sizes that are sold out will be greyed out and non-selectable to prevent users from adding sold-out inventory to the shopping cart.

## **Tasks**

- [ ] Render a grid of clickable shoe sizes buttons on the product detail page.
- [ ] Ensure the grid displays the correct shoe sizes for each shoe.
- [ ] Implement functionality to add the selected shoe and size to the shopping cart when a size is clicked.
- [ ] Grey out and disable selection for sold-out sizes.
- [ ] Test the size selection and add-to-cart functionality to ensure it works correctly.
