### ISSUE TITLE
User Stories - Sale Section

### ISSUE THREAD

**Issue by ShaneDoyleDev** [ShaneDoyleDev/fleetfoot#33]
# EPIC: **Viewing and Navigation**

As a **user**, I can **see an overview of some of the products that are on sale** so that **I can easily find discounted items and take advantage of sales**.

T-Shirt Size: **L**

## **Acceptance Criteria**

- Fetch and show nine shoes that are currently on sale in the store to feature in a section on the homepage.
- Render them using a slider component so that the user can scroll through them without the section taking up too much space.
- The user should be able to scroll back and forth using touch gestures on mobile.
- The slider will have forward and back buttons on either side that scroll through when clicked.
- The section is responsive for smaller screens.

## **Tasks**

- [x] Fetch nine shoes that are currently on sale in the store.
- [x] Design and implement a slider component to display the sale shoes.
- [x] Ensure the slider component supports touch gestures for mobile devices.
- [x] Add forward and back buttons to the slider for easy navigation.
- [x] Make the slider section responsive for smaller screens.
- [x] Test the functionality and responsiveness of the slider to ensure it meets the acceptance criteria.
