### ISSUE TITLE
 User Story - Account Logout

### ISSUE THREAD

**Issue by ShaneDoyleDev** [ShaneDoyleDev/fleetfoot#6]
# EPIC: **User Accounts and Authentication**

As a **user**, I want to **logout from my account**, so that **I can secure my account from unauthorized access and allow space for other potential users to login**.

**T-Shirt Size:** M

## **Acceptance Criteria**

- Users can easily locate and use a logout button from the navbar accessible from anywhere on the site.
- Users are asked to confirm their intent before logging out to prevent accidental sign-offs.
- Upon successful logout, users are redirected back to the home page.

## **Tasks**

- [] Design a user-friendly and accessible logout mechanism.
- [] Place a logout link in the main navbar.
- [] Implement a logout confirmation dialog to confirm the user's intent to sign out.
- [] Ensure that clicking the logout button on the confirmation dialog successfully signs out the user.
- [] Redirect the user to the home page immediately after logging out to confirm the process completion.
