### ISSUE TITLE
User Story - Product Sales

### ISSUE THREAD

**Issue by ShaneDoyleDev** [ShaneDoyleDev/fleetfoot#8]
# **EPIC:** Viewing and Navigation

As a **user**, I can **see which shoes are on sale** so that **I can potentially find a good deal on a shoe I may wish to purchase**.

T-Shirt Size: **M**

## Acceptance Criteria

- Have a section on the main homepage for showing shoes that are currently on sale.
- If an item is on sale, it will show the percentage off along with the sale price next to the product.
- Display sale information during the shopping cart and checkout process.

## Tasks

- [x] Have a section on the main homepage for showing shoes that are currently on sale.
- [x] Include fields on the product model for tracking if the product is on sale and discount percentage.
- [x] Update the product detail page and product cards to show the sale information prominently.
- [x] Ensure that the sale information is correctly displayed in the shopping cart and checkout process.
- [x] Show the sale price on the users order summary.
